#Dungeon Variables under here
Ruins = "Provisions: Holy Water, Skeleton Keys, Shovels and Medicinal Herbs. Bring extra food and torches.\n Enemies: Unholy.\n Blight attacks are useful while Bleed is not."
Warrens = "Provisions: Medicinal Herbs, Shovels, Holy Water and Bandages. Bring less food and torches.\n Enemies: Human/Beast.\n Bleed attacks are useful while Blight is not. Stress damage here is common and scouting is very useful due to layouts."
Weald = "Provisions: Bandages, Antivenom, Medicinal Herbs, Holy Water and Shovels. Bring less food.\n Enemies: Eldritch/Human/Beast.\n Bleed attacks are useful while Blight is not."
Cove = "Provisions: Medicinal Herbs, Shovels and Holy Water. Bring less food.\n Enemies: Eldritch/Unholy.\n Blight attacks are useful while Bleed is not. Enemies here stun and have high PROT and damage. Make sure your frontline has high PROT."

#Curio Variables under here
General_Curio = "GENERAL CURIOS: Eldritch Altar - Use Holy Water to purge a Negative Quirk or risk 40% chance of Stress +25.\n Heirloom Chest - Use a Skeleton Key or Antivenom to obtain Heirlooms or risk 12.5% chance of Blight or Bleed (75% chance of Heirloom).\n Stack of Books - DO NOT USE TORCH Stress +100. 22% chance Stress +25, 22.2% Random Positive Quirk, 11.1% Random Negative Quirk, 11.1% Decrease Light Meter by 25 or a Journal Page.\n Unlocked Strongbox - 75% Any Loot x2, 25% Blight.\n"
Ruins_Curio = "RUINS CURIOS: Alchemy Table - Use a Torch to increase light ro Medicinal Herbs for Gold/Gems or risk 50% Blight or 25% chance of Gold/Gems.\n Altar of Light - Use Holy Water for a 30% DMG buff or risk a 20% DMG buff.\n Bookshelf - 20% Scouting, 20% Stress +15, 13.3% Positive Quirk, Negative Quirk or 20% Journal Entry.\n Confession Booth - Use Holy Water for 30 Stress Heal or risk 50% Stress +15, 25% Gold/Trinket x6, 25% Purge Negative Quirk.\n Decorative Urn - Use Holy Water for Gems/Trinket and Shovel for Negative Quirk: Guilty Conscience or risk 44.4% Gems/Trinket x1 + Gems x2, 22.2% Blight, 7.4% Disease: Creeping Cough, 3.7% Random Disease or 22.2% Nothing.\n Holy Fountain - Use Holy Water for stress heal 20, heal 12HP and Cure Status Effects or risk 50% Stress Heal 10/Cure Status Effects/Heal 5HP, 50% Gold Gem x2.\n Iron Maiden - Use Medicinal Herbs for Loot x2 or risk 40% Any Loot x2, 20% Negative Quirk: Claustrophobia, 13.3% Disease: Tetanus, 6.7% Random Disease.\n Locked Display Cabinet - Use Skeleton Key or Shovel for Gold/Heirlooms x3 + Gold/Gems x2 or risk 50% chance of Bleed or Blight.\n Locked Sarcophagus - Use Skeleton Key or Shovel for Gold/Heirlooms x3 + Gold/Gems x2 or risk 50% chance of Bleed or Blight.\n Sarcophagus - Risk 60% Gold/Heirlooms x2,Negative Quirk: Thanatophobia.\n"
Warrens_Curio = "Dinner Cart - Use Medicinal Herbs for Food x3 + Gold/Trinket x1 or risk 37.5% Food x1 + Gold/Trinket x1, 25% Blight, 12.5% Disease: The Black Plague.\n Makeshift Dining Table - Use Medicinal Herbs for Food x2 + Gold/Supplies x1 or risk 25% Food x1 + Gold/Supplies x1,25% Blight or Disease: Tapeworm.\n Moonshine Barrel - Use Medicinal Herbs for Buff +30% DMG (until camp) or risk 33.3% Food x1 + Gold/Supplies x1, 33.3% Blight, 11.1% Negative Quirk: Tippler.\n Occult Scrawlings - Do not use Holy Water it creates Debuff -20% DODGE or risk 33.3% Random Positive Quirk, 25% Stress +25, 16.7% Random Negative Quirk.\n Pile of Bones - Use Holy Water for any Loot x2 or risk 25% Any Loot x2, 25% Random Disease, 25% Negative Quirk: Bloodthirsty.\n Pile of Scrolls - Use Torch to purge Negative Quirk or risk 28.6% Scouting, 14.3% Stress +15, 9.5% Random Positive Quirk, 4.8% Random Negative Quirk.\n Rack of Blades - Use Banadages for Gold/Gems x2 + Food x1, 40% Gold/Gems x1 + Food x1, 40% Bleed.\n Sacrificial Stone - Risk 50% Stress +50, 25% Purge Negative Quirk, 12.5% Positive Quirk: Warrens Explorer, 12.5% Positive Quirk: Warrens Scrounger.\n"
Weald_Curio = "Ancient Coffin - Risk 50% Gold/Heirloom x2, 8.3% Positive Quirk: Weald Adventurer, 8.3% Positive Quirk: Weald Explorer.\n Beast Carcass = Use Medicinal Herbs for Food x2 or risk 42.9% Food x1, 9.5% Disease: Rabies, 19% Random Disease, 14.3% Negative Quirk: Zoophobia.\n Eerie Spiderweb = Use Bandages for Gold/Gems x2 + Gems/Trinket x1 or risk 40% Gold/Gems x1 + Gems/Trinket x1, 10% Negative Quirk: Slow Reflexes, 10% Negative Quirk: Slowdraw.\n Left Luggage = Use Antivenom or Skeleton key for 3x Loot or risk 50% any loot or Blight.\n Mummified Remains = Use Bandages for Gold/Trinkets x2 or risk 40% Gold/Trinkets x1, 40% Blght.\n Old Tree = Use Antivenom for Any Loot x3 or risk 50% Any Loot x2, 25% Blight.\n Shallow Grave = Use a Shovel for Gems/Heirlooms x3 or risk 50% Blight or Random Disease.\n Travelers Tent = Risk 37.5% Gold/Supplies x4 + Gold/Heirlooms x4, 37.5% Scouting, 12.5% Stress +25.\n Troubling Effigy = Use Holy Water for a Positive Quirk or risk 18.8% Positive Quirk or Negative Quirk or Bleed,9.4% Blight or Stress +15.\n"
Cove_Curio = "Barnacle Crusted Chest - Use Shovel for Any Loot x3 or risk 50% Any loot x2,25% Bleed.\n Bas-Relief - DO NOT USE SHOVEL or recieve Stress +100 or risk 66.7% Positive Quirk, 22.2% Negative Quirk, 11.1% Disease chance.\n Brackish Tide Pool - Use Antivenom for 50% stress heal or HP or risk 75% BUFF 33% blight/bleed/disease resist, 25% random disease.\n Eerie Coral - Use Medicinal Herbs for Purge Negative Quirk or risk 50% Stress Heal 10, 25% Stress +25.\n Fish Idol - Use Holy Water for Buff +18% DMG until Camp or risk Debuff -25% DMG, -10 ACC until Camp, 50% Debuff -12 DODGE until Camp.\n Fish Carcass - Use Medicinal Herbs for Gem/Trinkets x2 + Gem/Gold x1 + Supplies x2 or risk 16.7% Gem/Trinkets x1 Gold/Gem x1 + Supply x1, 16.7% Disease, 11.1% Blight, 5.6% Bleed.\n Giant Oyster - Use Shsovel for gold/trinkets or dog treats for +25 Dodge buff or risk 40% gold/trinkets, 40% Bleed./n"

#Program under here
def greet (lang):
    if lang == "es":
        print("Hola")
    elif lang == 'fr':
        print('Bonjour')
    else:
        print('Not an option')

print('what lang?\n')
lang = input:(es?)
    greet
